language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: {PUT_YOUR_OWN_API_KEY_HERE}
  app: fierce-eyrie-80221
  on:
    repo: manuelleungchen/unittest-travis-heroku